// The explicit review routes, not arbitrary imported project IDs or URLs.
export const AUTHORED_JOURNEY_ROUTE_IDS = Object.freeze([
  "coupa-all",
  'opening',
  'authored',
  'whole-originals',
  'whole-originals-v2',
  'whole-originals-v3',
  'whole-originals-v4',
  'whole-spatial-v1',
  'whole-spatial-v2',
  'whole-spatial-v3',
  'whole-spatial-v4',
  'whole-spatial-v5',
  'whole-spatial-v6',
  'whole-spatial-v7',
  'whole-spatial-v8',
  'whole-spatial-v9',
  'whole-spatial-v10',
  'whole-spatial-v11',
  'whole-spatial-v12',
  'whole-spatial-v13',
  'whole-spatial-v14',
  'whole-spatial-v15',
  'whole-spatial-v16',
  'whole-spatial-v17',
  'whole-spatial-v18',
  'whole-spatial-v19',
  'whole-spatial-v20',
  'whole-spatial-v21',
  'whole-spatial-v22',
  'whole-spatial-v23',
  'whole-spatial-v24',
  'whole-spatial-v25',
  'whole-spatial-v26',
  'whole-spatial-v27',
  'whole-spatial-v28',
  'whole-spatial-v29',
  'whole-spatial-v30',
  'whole-spatial-v31',
  'whole-spatial-v32',
  'whole-spatial-v33',
  'whole-spatial-v34',
  'whole-spatial-v35',
  'whole-spatial-v36',
  'whole-spatial-v37',
  'whole-spatial-v38',
  'whole-ornament-v1',
  'whole-ornament-v2',
]);
export const isAuthoredJourneyRouteId = (id) => AUTHORED_JOURNEY_ROUTE_IDS.includes(id);
export const authoredJourneyUsesActorMaterials = (id) =>
  [
    'whole-originals-v4',
    'whole-spatial-v1',
    'whole-spatial-v2',
    'whole-spatial-v3',
    'whole-spatial-v4',
    'whole-spatial-v5',
    'whole-spatial-v6',
    'whole-spatial-v7',
    'whole-spatial-v8',
    'whole-spatial-v9',
    'whole-spatial-v10',
    'whole-spatial-v11',
    'whole-spatial-v12',
    'whole-spatial-v13',
    'whole-spatial-v14',
    'whole-spatial-v15',
    'whole-spatial-v16',
    'whole-spatial-v17',
    'whole-spatial-v18',
    'whole-spatial-v19',
    'whole-spatial-v20',
    'whole-spatial-v21',
    'whole-spatial-v22',
    'whole-spatial-v23',
    'whole-spatial-v24',
    'whole-spatial-v25',
    'whole-spatial-v26',
    'whole-spatial-v27',
    'whole-spatial-v28',
    'whole-spatial-v29',
    'whole-spatial-v30',
    'whole-spatial-v31',
    'whole-spatial-v32',
    'whole-spatial-v33',
    'whole-spatial-v34',
    'whole-spatial-v35',
    'whole-spatial-v36',
    'whole-spatial-v37',
    'whole-spatial-v38',
    'whole-ornament-v1',
    'whole-ornament-v2',
  ].includes(id);

/** Fixed same-game destinations. Team has different authored missions and is
 * intentionally not inferred from a Solo/Versus route. This is navigation only:
 * no save, token, mission completion or cross-mode progress transfer. */
export function authoredJourneyModeHref(routeId, destination) {
  if (!isAuthoredJourneyRouteId(routeId)) return null;
  if (destination === 'versus') return `couch/?journey=${routeId}&return=solo`;
  if (destination === 'solo') return `../?journey=${routeId}`;
  return null;
}
