import path from 'node:path';
import { readFileSync } from 'node:fs';
import { parse } from 'acorn';
import { parse as parseHTML, serialize } from 'parse5';

// This is the deliberately small downstream policy layer. Every source edit
// matches a reviewed structural boundary; upstream drift stops synchronization.
const encoder = (value) => Buffer.from(value);
const json = (value) => encoder(JSON.stringify(value) + '\n');
const hiddenIds = [
  'shell-home-fpv', 'shell-home-practice', 'shell-optional-practice',
  'shell-team', 'shell-versus', 'shell-title-team', 'shell-title-versus', 'shell-mode-choice',
  'shell-controller-lab', 'shell-replay-theater', 'shell-release-explorer', 'shell-catalogue', 'shell-guide',
  'shell-asset-studio', 'shell-playground', 'shell-enemy-catalog', 'shell-motion-lab',
  'shell-still-media', 'shell-video-poster', 'shell-design-atlas', 'creator-tools',
  'native-diagnostics', 'shell-offline', 'settings-offline', 'offline-button',
  'first-flight-help-enter', 'first-flight-enter', 'first-flight-entry',
  'library-packs', 'library-saves', 'pack-file', 'pack-json', 'install-pack',
  'save-file', 'save-json', 'import-save', 'undo-library', 'undo-backup',
  'shell-workshop', 'settings-tab-content', 'settings-panel-content', 'settings-saves', 'soundtrack-open',
];
const hiddenSelectors = [
  ...hiddenIds.map((id) => `#${id}`),
  '[data-library-panel="packs"]', '[data-library-panel="saves"]',
  '[data-release-explorer]', '[data-source-only]', '.workshop-tools',
  '.edition-offline', '.optional-practice-dialog', '[data-branded-unavailable]',
];

function walk(node, visit) {
  if (!node || typeof node !== 'object') return;
  visit(node);
  for (const child of Object.values(node)) {
    if (Array.isArray(child)) child.forEach((entry) => walk(entry, visit));
    else if (child && typeof child === 'object') walk(child, visit);
  }
}

function edit(files, name, transform) {
  if (!files.has(name)) throw new Error(`Isolation boundary missing: ${name}`);
  files.set(name, encoder(transform(files.get(name).toString('utf8'))));
}

function once(source, search, replacement, description) {
  const first = source.indexOf(search);
  if (first < 0 || source.indexOf(search, first + search.length) !== -1)
    throw new Error(`Upstream changed isolation boundary: ${description}`);
  return source.slice(0, first) + replacement + source.slice(first + search.length);
}

function removeImports(source, specifiers) {
  const tree = parse(source, { ecmaVersion: 'latest', sourceType: 'module' });
  const nodes = tree.body.filter((node) =>
    node.type === 'ImportDeclaration' && specifiers.includes(node.source.value));
  if (nodes.length !== specifiers.length) throw new Error('Upstream changed shell imports.');
  for (const node of nodes.reverse()) source = source.slice(0, node.start) + source.slice(node.end);
  return source;
}

function functionGuard(source, name, guard) {
  const tree = parse(source, { ecmaVersion: 'latest', sourceType: 'module' });
  const matches = [];
  walk(tree, (node) => {
    if (node.type === 'FunctionDeclaration' && node.id?.name === name) matches.push(node);
  });
  if (matches.length !== 1) throw new Error(`Upstream changed function boundary: ${name}`);
  const position = matches[0].body.start + 1;
  return source.slice(0, position) + '\n' + guard + '\n' + source.slice(position);
}

function policyModule(config, catalog) {
  const settings = {
    editionId: config.editionId,
    brandId: config.brandId,
    repo: config.repo,
    campaignIds: catalog.campaigns.map(({ id }) => id),
    presentationIds: catalog.editions[0].presentationHistory?.map(({ id }) => id) ?? [],
  };
  return `// Generated by scripts/isolate-brand.mjs. Never hand-edit generated app files.
export const BRAND_POLICY = Object.freeze(${JSON.stringify(settings)});
export const UNAVAILABLE_SELECTORS = ${JSON.stringify(hiddenSelectors)};
const unavailable = 'This dedicated community app only supports its included campaigns.';
export function assertBrandedPacks(packs) {
  if (!packs || !Array.isArray(packs.packs) || packs.packs.length) throw new TypeError(unavailable);
  return packs;
}
export function denyBrandedImport() { throw new TypeError(unavailable); }
export function assertBrandedLocation(href) {
  const url = new URL(href), params = url.searchParams;
  const allowed = new Set(['edition', 'campaign', 'presentation', 'lang', 'controllerTrace', 'journey']);
  for (const key of params.keys()) {
    if (!allowed.has(key) || params.getAll(key).length !== 1) throw new TypeError(unavailable);
  }
  if (params.has('edition') && params.get('edition') !== BRAND_POLICY.editionId) throw new TypeError(unavailable);
  if (params.has('campaign') && !BRAND_POLICY.campaignIds.includes(params.get('campaign'))) throw new TypeError(unavailable);
  if (params.has('presentation') && !BRAND_POLICY.presentationIds.includes(params.get('presentation'))) throw new TypeError(unavailable);
  if (params.has('journey') && params.get('journey') !== BRAND_POLICY.editionId && params.get('journey') !== '1') throw new TypeError(unavailable);
  return url;
}
export function brandedHrefAllowed(href, baseHref) {
  try {
    const base = new URL(baseHref), target = new URL(href, base);
    const root = new URL('./', base);
    if (target.origin !== base.origin || target.username || target.password) return false;
    if (!['', 'index.html', 'company.html'].some((entry) => target.pathname === root.pathname + entry)) return false;
    assertBrandedLocation(target.href);
    return true;
  } catch { return false; }
}
export function installBrandedIsolation(doc = globalThis.document, win = globalThis.window) {
  if (!doc || !win || doc.documentElement.dataset.brandedIsolationInstalled) return;
  doc.documentElement.dataset.brandedIsolationInstalled = 'true';
  const conceal = (element) => {
    if (!element.hidden) element.hidden = true;
    if (element.hasAttribute('href')) element.removeAttribute('href');
    if ('disabled' in element && !element.disabled) element.disabled = true;
    if (!element.hasAttribute('data-branded-unavailable')) element.setAttribute('data-branded-unavailable', '');
  };
  const refresh = () => {
    for (const element of doc.querySelectorAll(UNAVAILABLE_SELECTORS.join(','))) conceal(element);
    for (const link of doc.querySelectorAll('a[href]')) {
      const href = link.getAttribute('href');
      if (link.hasAttribute('download') && /^(?:blob:|data:)/.test(href)) continue;
      if (!brandedHrefAllowed(href, win.location.href)) conceal(link);
    }
  };
  doc.addEventListener('click', (event) => {
    const target = event.target?.closest?.('a,button,input,select');
    if (!target) return;
    if (target.closest(UNAVAILABLE_SELECTORS.join(',')) ||
        (target.matches('a[href]') && !target.hasAttribute('download') && !brandedHrefAllowed(target.href, win.location.href))) {
      event.preventDefault(); event.stopImmediatePropagation();
    }
  }, true);
  refresh();
  const observer = new win.MutationObserver(refresh);
  observer.observe(doc.documentElement, {childList: true, subtree: true, attributes: true, attributeFilter: ['href', 'hidden', 'disabled']});
  win.addEventListener('pagehide', () => observer.disconnect(), {once: true});
}
`;
}

function scopeStorage(source, repo) {
  // Storage keys, lock names and internal notification topics are deliberately
  // separate from portable format strings (revealline-*.vN), content IDs and pins.
  const names = [
    'actor-style', 'audio-master', 'company', 'company-accessibility', 'company-installed',
    'company-learning', 'company-learning-draft', 'company-learning-proofs', 'display', 'encounter-display',
    'couch-controller-profiles', 'couch-radio-setup', 'game-activity', 'creator', 'playground',
    'flight-profiles', 'gameplay-tuning', 'install-suggestion', 'installed-app',
    'journey-mastery-proofs', 'journey-preferences', 'journey-reactions', 'library',
    'locale', 'menu-animation', 'menu-audio', 'menu-style', 'mission-goal',
    'mission-library', 'mode-return', 'movement-audio', 'music-shortcuts',
    'official-downloads', 'offline-panel', 'packs', 'player', 'profile', 'progress',
    'radio-audio', 'session', 'settings', 'solo-radio-profiles', 'solo-radio-setup',
    'suspended', 'touch', 'window', 'demo',
  ];
  for (const name of names)
    source = source.replace(new RegExp('revealline\\.' + name.replaceAll('-', '\\-') + '(?=[.\'"\x60])', 'g'), `${repo}.${name}`);
  return source
    .replaceAll("startsWith('revealline.')", `startsWith('${repo}.')`)
    .replaceAll('revealline\\.', `${repo}\\.`)
    .replaceAll('revealline-journey-v1', `${repo}-journey-v1`)
    .replaceAll('revealline-soundtrack-v1', `${repo}-soundtrack-v1`)
    .replaceAll('revealline-assets-v1', `${repo}-assets-v1`)
    .replaceAll('revealline-demo-recordings-v1', `${repo}-demo-recordings-v1`)
    .replaceAll('revealline-official-content-v1', `${repo}-official-content-v1`)
    .replaceAll('revealline-official-downloads-v1', `${repo}-official-downloads-v1`)
    .replaceAll('revealline-official-original-index-v1', `${repo}-official-original-index-v1`)
    .replaceAll('/.revealline-official/', `/.${repo}-official/`);
}

function projectHTML(source, name, config) {
  const document = parseHTML(source);
  const visit = (node) => {
    if (node.childNodes) node.childNodes = node.childNodes.filter((child) =>
      !(child.tagName === 'link' && child.attrs?.some((entry) =>
        ['href', 'data-boot-href'].includes(entry.name) && /optional-practice-panel\.css$/.test(entry.value))));
    if (node.attrs) {
      const attr = (key) => node.attrs.find((entry) => entry.name === key)?.value;
      const add = (key, value = '') => {
        node.attrs = node.attrs.filter((entry) => entry.name !== key);
        node.attrs.push({ name: key, value });
      };
      const blocked = hiddenIds.includes(attr('id')) ||
        ['packs', 'saves'].includes(attr('data-library-panel')) ||
        attr('data-release-explorer') !== undefined || attr('data-source-only') !== undefined;
      if (node.tagName === 'select' && attr('id') === 'menu-actor-style')
        node.childNodes = node.childNodes.filter((child) => child.tagName !== 'option' ||
          child.attrs?.some((entry) => entry.name === 'value' && entry.value === 'campaign'));
      if (node.tagName === 'option' && attr('data-i18n') === 'interface:fpvFieldKit') {
        node.attrs = node.attrs.filter((entry) => entry.name !== 'data-i18n');
        node.childNodes = [{nodeName:'#text', value:'Field Kit', parentNode:node}];
      }
      if (blocked) {
        add('hidden'); add('data-branded-unavailable');
        if (['button', 'input', 'select', 'textarea'].includes(node.tagName)) add('disabled');
      }
      if (node.tagName === 'a' && attr('href') !== undefined) {
        const target = new URL(attr('href'), `https://brand.invalid/${name}`);
        if (target.origin !== 'https://brand.invalid' ||
            !['/game/', '/game/index.html', '/game/company.html'].includes(target.pathname) || blocked) {
          node.attrs = node.attrs.filter((entry) => entry.name !== 'href');
          add('hidden'); add('data-branded-unavailable');
        } else {
          target.search = `?edition=${config.editionId}`;
          add('href', './' + target.search + target.hash);
        }
      }
      if (node.tagName === 'html') add('data-branded-app', config.repo);
    }
    node.childNodes?.forEach(visit);
  };
  visit(document);
  return serialize(document).replace('</head>',
    `<style>${hiddenSelectors.join(',')}{display:none!important}</style></head>`);
}

function projectLanding(files) {
  // Presentation-only customization. Keep official artwork bytes, campaign
  // identities and the upstream menu's accessibility/lifecycle contracts.
  const css = readFileSync(new URL('../branding/coupa-landing.css', import.meta.url));
  const art = readFileSync(new URL('../branding/coupa-landing.html', import.meta.url), 'utf8');
  files.set('game/ui/coupa-landing.css', css);
  edit(files, 'game/index.html', (source) => once(once(source,
    '<div class="home-art" aria-hidden="true"></div>', art, 'Coupa landing decoration'),
    '</head>', '<link rel="stylesheet" href="ui/coupa-landing.css"></head>', 'Coupa landing styles'));
  edit(files, 'game/ui/edition-solo.mjs', (source) => once(source,
    "logo.className = 'edition-home-logo';",
    "logo.className = 'edition-home-logo coupa-landing-logo';", 'Coupa landing logo'));
  edit(files, 'game/ui/menu-scene-catalog.mjs', (source) => once(source,
    'if (!composition) return profile;', `if (!composition) return {
    ...profile,
    landscape: '../editions/assets/coupa/wallpaper-network-2024.png',
    portrait: '../editions/assets/coupa/wallpaper-network-2024.png',
    landscapePosition: '72% 50%', portraitPosition: '82% 50%',
    environment: [], portraitEnvironment: [], actorVisible: false,
    signalOpacity: 0, signalPeakOpacity: 0,
  };`, 'Coupa official wallpaper'));
  // The new CSS capture trails own ambient motion. Keep the upstream motion
  // switch, reduced-motion, visibility and dialog pause lifecycle, without
  // starting photograph distortion or analog interference renderers.
  edit(files, 'game/ui/menu-scenes.mjs', (source) => once(source,
    '    if (running && !artworkMotion) {', '    if (false && running && !artworkMotion) {', 'Coupa static wallpaper renderer'));
  edit(files, 'game/ui/menu-scenes.mjs', (source) => once(source,
    '    if (running && !signalLoss) {', '    if (false && running && !signalLoss) {', 'Coupa clean wallpaper'));
  edit(files, 'game/app.mjs', (source) => once(source,
    "container: $('shell-home')?.querySelector('.home-content'),",
    'container: null, // The dedicated landing uses its official rotating Coupa mark.', 'Coupa landing character'));
}

function pruneUnreachableModules(files) {
  const pending = ['game/app.mjs', 'game/boot.mjs', 'game/company-entry.mjs'];
  for (const [name, bytes] of files) {
    if (!name.endsWith('.html')) continue;
    for (const match of bytes.toString().matchAll(/\b(?:src|data-module)=["']([^"']+\.(?:mjs|js))["']/g))
      pending.push(path.posix.normalize(path.posix.join(path.posix.dirname(name), match[1])));
  }
  const visited = new Set();
  while (pending.length) {
    const name = pending.pop();
    if (visited.has(name) || !files.has(name)) continue;
    visited.add(name);
    const tree = parse(files.get(name).toString(), { ecmaVersion: 'latest', sourceType: 'module', allowHashBang: true });
    walk(tree, (node) => {
      const target = ['ImportDeclaration', 'ExportNamedDeclaration', 'ExportAllDeclaration', 'ImportExpression'].includes(node.type)
        ? node.source?.value
        : node.type === 'NewExpression' && node.callee?.name === 'URL' ? node.arguments[0]?.value : null;
      if (typeof target === 'string' && /^\.{1,2}\//.test(target) && /\.(?:mjs|js)$/.test(target))
        pending.push(path.posix.normalize(path.posix.join(path.posix.dirname(name), target)));
    });
  }
  for (const name of files.keys())
    if (/\.(?:mjs|js)$/.test(name) && !visited.has(name)) files.delete(name);
}

export function isolateBrand(input, config) {
  if (!(input instanceof Map) || !/^[a-z][a-z0-9-]+$/.test(config.repo))
    throw new TypeError('An isolated brand needs a file map and stable application identity.');
  const files = new Map(input);
  const catalog = JSON.parse(files.get('edition-catalog.json'));
  if (catalog.editions.length !== 1 || catalog.editions[0].id !== config.editionId ||
      catalog.brands.length !== 1 || catalog.brands[0].id !== config.brandId ||
      catalog.campaigns.some((entry) => entry.brandId !== config.brandId))
    throw new Error('The compiler did not select exactly the dedicated brand.');
  files.set('game/branded-isolation.mjs', encoder(policyModule(config, catalog)));
  edit(files, 'game/runtime-content-provider.mjs', (source) => {
    source = `import { assertBrandedLocation } from './branded-isolation.mjs';\n` + source;
    return once(source, '  const sourceURL = new URL(locationRef.href);',
      '  const sourceURL = assertBrandedLocation(locationRef.href);', 'provider URL');
  });
  edit(files, 'game/app.mjs', (source) => {
    source = `import { installBrandedIsolation, assertBrandedLocation, assertBrandedPacks, denyBrandedImport } from './branded-isolation.mjs';\n` + source;
    source = once(source, '  const previewSession = createStudioPreviewSession(location.href);',
      '  assertBrandedLocation(location.href);\n  const previewSession = createStudioPreviewSession(location.href);', 'pre-preview startup');
    source = once(source, '  const runtimeContent = await loadCompanyStartup();',
      '  installBrandedIsolation(document, window);\n  const runtimeContent = await loadCompanyStartup();', 'host startup');
    source = functionGuard(source, 'prepareContentCatalog', '    assertBrandedPacks(nextPacks);');
    source = functionGuard(source, 'replacePackLibrary', '    assertBrandedPacks(next);');
    for (const boundary of ['    setLibrary: (next) => {', '    applyBackup: async (prepared) => {'])
      source = once(source, boundary, boundary + '\n      denyBrandedImport();', boundary);
    // Registered training and reusable controller mechanisms remain upstream
    // engine code; no training/course content can be entered in this product.
    source = functionGuard(source, 'enterFirstFlight', '    denyBrandedImport();');
    source = functionGuard(source, 'initializeSoundtrack',
      "    soundtrackLoading = false;\n    soundtrackStatus('Campaign music ready.');\n    return; // Dedicated editions use their authored procedural soundtrack.");
    return source;
  });
  edit(files, 'game/ui/library-panel.mjs', (source) => {
    source = `import { denyBrandedImport } from '../branded-isolation.mjs';\n` + source;
    source = functionGuard(source, 'install', '    denyBrandedImport();');
    return functionGuard(source, 'importSave', '    denyBrandedImport();');
  });
  edit(files, 'game/ui/game-shell.mjs', (source) => {
    source = removeImports(source, ['../fpv-entry.mjs', './optional-practice-panel.mjs', '../release-explorer.mjs']);
    const start = source.indexOf('  const optionalPractice = !isolated');
    const end = source.indexOf('  const deck =', start);
    if (start < 0 || end < 0) throw new Error('Upstream changed optional practice shell.');
    return source.slice(0, start) +
      "  const optionalPractice = null;\n  const homeFPV = $('shell-home-fpv');\n  const homePractice = $('shell-home-practice');\n" + source.slice(end);
  });
  files.set('game/ui/edition-navigation.mjs', encoder(`import { installBrandedIsolation } from '../branded-isolation.mjs';
export function mountEditionNavigation({provider, document: doc}) {
  for (const link of doc.querySelectorAll('a[href]')) {
    const target = new URL(link.getAttribute('href'), provider.href());
    const base = new URL(provider.href());
    if (target.origin === base.origin && ['index.html', 'company.html', ''].some((entry) => target.pathname === new URL('./', base).pathname + entry))
      link.href = provider.href() + target.hash;
  }
  installBrandedIsolation(doc, doc.defaultView ?? globalThis.window);
}
`));
  edit(files, 'game/ui/edition-solo.mjs', (source) => once(source,
    "if (!previewSession && root.dataset.editionId && version !== 'DEV') {",
    'if (false) { // Dedicated web app does not publish the upstream edition launcher.', 'edition offline launcher'));
  edit(files, 'game/ui/brand-identity.mjs', (source) => once(source,
    "export const GAME_BRAND_NAME = 'FPV / LINE';",
    `export const GAME_BRAND_NAME = ${JSON.stringify(config.name)};`, 'brand fallback'));
  const brandIcon = catalog.assets.find((asset) => asset.id === catalog.brands[0].iconAssetId);
  if (!brandIcon) throw new Error('The dedicated brand must provide a browser icon.');
  edit(files, 'game/ui/brand-identity.css', (source) => once(source,
    './art/identity/fpv-line/icon-192.png',
    path.posix.relative('game/ui', brandIcon.path), 'shared brand CSS icon'));
  // Full-game public routing has no role in a pinned edition, and must not
  // carry a discoverable registry of other communities into the derivative.
  files.set('game/community-routes.mjs', encoder(`export const COMMUNITY_ROUTES = Object.freeze([]);
export function communityRouteFromURL() { return null; }
export function communityHref() { return null; }
export function communityEntryURL() { throw new TypeError('Community selection is unavailable.'); }
export function gameDocumentURL(href) { const source = new URL(href), target = new URL('index.html', source); target.search = source.search; target.hash = source.hash; return target; }
`));
  files.set('game/content/soundtrack-catalogue.mjs', encoder(`// Community apps retain authored campaign music; the public recording archive is not distributed.
export const SOUNDTRACK_CATALOGUE = Object.freeze({format:'revealline-soundtrack-catalogue.v2',edition:'${config.editionId}',tracks:[]});
export const SOUNDTRACK_ARCHIVES = Object.freeze([]);
export const SOUNDTRACK_COLLECTIONS = Object.freeze([]);
export const SOUNDTRACK_BUNDLED_ASSETS = Object.freeze([]);
`));
  files.set('game/ui/soundtrack-panel.mjs', encoder(`// The dedicated game has campaign music and normal volume controls only.
export function attachSoundtrackPanel() { throw new TypeError('The public music library is unavailable in this community app.'); }
`));
  files.set('game/first-flight.mjs', encoder(`// Standalone general-flight course content is excluded from this community app.
import { denyBrandedImport } from './branded-isolation.mjs';
export const FIRST_FLIGHT_LESSONS = Object.freeze([]);
export function resolveCourseRequest() { return null; }
export const getFirstFlightLesson = denyBrandedImport;
export const createLessonScenario = denyBrandedImport;
export const captureLessonFacts = denyBrandedImport;
export const createLessonObserver = denyBrandedImport;
`));
  // The original demo catalogue embeds unrelated first-game missions. Live
  // demonstrations of the selected mission remain available through the engine.
  if (files.has('game/demo-data/catalog.json'))
    files.set('game/demo-data/catalog.json', json({ format: 'revealline-demo-catalog.v1', clips: [] }));
  if (files.has('game/demo-data/variant-provenance.json'))
    files.set('game/demo-data/variant-provenance.json', json({ recordings: [] }));
  for (const name of [...files.keys()]) {
    if (/^game\/(?:controller-lab|replay-theater)\/.*\.(?:html|css)$/.test(name) ||
        /^game\/ui\/art\/identity\/fpv-line\//.test(name) ||
        /^game\/demo-data\/.*\.replay\.json$/.test(name) ||
        /^game\/audio\/soundtracks\/.*\.mp3$/.test(name) ||
        /^game\/(?:fpv-entry|optional-practice[^/]*|ui\/optional-practice-panel)\.(?:mjs|css)$/.test(name)) files.delete(name);
  }
  for (const [name, bytes] of files) {
    if (/\.(?:mjs|js)$/.test(name)) files.set(name, encoder(scopeStorage(bytes.toString('utf8'), config.repo)));
    if (name.endsWith('.html')) files.set(name, encoder(projectHTML(bytes.toString('utf8'), name, config)));
  }
  projectLanding(files);
  pruneUnreachableModules(files);
  // The upstream compiler appends shared presentation ledger records, some of
  // which became unused after removing its public archive/default identity.
  // Remove only unowned runtime records; selected brand/campaign pins may never
  // silently lose bytes during projection.
  const removedAssetIds = new Set(catalog.assets.filter((asset) => !files.has(asset.path)).map((asset) => asset.id));
  const ownedAssetIds = new Set([...catalog.brands, ...catalog.editions, ...catalog.campaigns].flatMap((entry) =>
    [...(entry.assetIds ?? []), ...['heroAssetId', 'logoAssetId', 'fontAssetId', 'iconAssetId'].map((key) => entry[key]).filter(Boolean)]));
  for (const id of removedAssetIds)
    if (!id.startsWith('runtime-') || ownedAssetIds.has(id) || catalog.assets.some((asset) =>
      !removedAssetIds.has(asset.id) && asset.dependencies.includes(id)))
      throw new Error(`Projection would remove selected presentation bytes: ${id}`);
  catalog.assets = catalog.assets.filter((asset) => !removedAssetIds.has(asset.id));
  files.set('edition-catalog.json', json(catalog));
  const title = config.name.replace(/[<>&"]/g, '');
  files.set('index.html', encoder(`<!doctype html><html lang="en" data-branded-app="${config.repo}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${title}</title></head><body><main><h1>${title}</h1><p id="entry-status">Opening your Coupa campaign…</p><a href="game/index.html?edition=${config.editionId}">Play ${title}</a></main><script type="module">import { assertBrandedLocation } from './game/branded-isolation.mjs'; try { assertBrandedLocation(location.href); const target = new URL('game/index.html', location.href); target.search = location.search; target.hash = location.hash; location.replace(target); } catch (error) { document.getElementById('entry-status').textContent = error.message; }</script></body></html>`));
  // Journey's IndexedDB is now application-specific; keep logical profile and
  // content IDs unchanged so upstream updates retain compatibility.
  const dependencies = JSON.parse(files.get('runtime-dependencies.json'));
  dependencies.resources = dependencies.resources.filter((name) => files.has(name));
  dependencies.resources.push('game/branded-isolation.mjs');
  dependencies.resources.push('game/ui/coupa-landing.css');
  files.set('runtime-dependencies.json', json(dependencies));
  validateBrandIsolation(files, config);
  return files;
}

export function validateBrandIsolation(files, config) {
  const catalog = JSON.parse(files.get('edition-catalog.json'));
  if (catalog.editions.length !== 1 || catalog.editions[0].id !== config.editionId ||
      catalog.brands.length !== 1 || catalog.brands[0].id !== config.brandId ||
      catalog.campaigns.some((entry) => entry.brandId !== config.brandId))
    throw new Error('Foreign audience entered the dedicated artifact.');
  for (const name of files.keys()) {
    if (/^(?:optional-practice\/|game\/(?:communities|community|couch)\/.*\.html$)/.test(name) ||
        /^game\/(?:fpv-entry|optional-practice[^/]*|ui\/optional-practice-panel)\.(?:mjs|css)$/.test(name) ||
        (/\.html$/.test(name) && !['index.html', 'game/index.html', 'game/company.html'].includes(name)))
      throw new Error(`Unrelated destination entered the dedicated artifact: ${name}`);
  }
  if (!files.get('game/profile-database.mjs')?.toString().includes(`${config.repo}-journey-v1`) ||
      !files.get('game/edition-context.mjs')?.toString().includes(`${config.repo}.library.`))
    throw new Error('The branded app must have its own browser storage identity.');
  return true;
}

export const validateIsolation = validateBrandIsolation;
